"""Constrained RPA utilities for the zero-field TBG workflow."""

from .band_classifier import BandClassification, classify_flat_bands
from .bm import AllBandBMSolution, read_all_band_bm_solution, solve_all_band_bm_model, write_all_band_bm_solution
from .coulomb import CRPACoulombParams, coulomb_potential_mev, coulomb_potential_table_mev
from .dielectric import DielectricResult, compute_dielectric
from .diagnostics import write_all_epsilon_diagnostics, write_crpa_epsilon_diagnostics_csv
from .flat_remote import (
    apply_chi0_energy_mode,
    apply_eq19_flat_remote_correction,
    apply_hf_active_flat_basis,
    normalize_chi0_energy_mode,
)
from .grid import CRPAKGrid, build_q_shift_table, build_uniform_crpa_grid
from .screened_coulomb import CRPAScreenedCoulomb
from .susceptibility import (
    compute_constrained_chi0,
    compute_constrained_chi0_by_subtraction,
    compute_flat_flat_chi0,
    compute_full_chi0,
    constrained_sum_identity_error,
)
from .workflow import CRPAResult, compute_crpa, load_crpa_result, write_crpa_outputs
from .hf_validation import has_full_crpa_q_table, validate_hf_compatible_crpa
from .hf_interface import (
    active_lower_flat_projector_like,
    build_bare_split_full_hf_kernel,
    build_bare_projected_interaction_components,
    build_bare_projected_target_components,
    build_crpa_hartree_delta_fock_projector_components,
    build_crpa_projected_interaction_components,
    build_crpa_projected_interaction_hamiltonian,
    build_crpa_projected_target_components,
    build_crpa_projected_target_components_from_densities,
    build_crpa_projected_target_hamiltonian,
    build_fock_screened_overlap_blocks,
    build_full_crpa_hf_kernel,
    crpa_active_density_from_delta,
    crpa_hartree_delta_fock_projector_energy_components,
    crpa_remote_bare_scale,
    crpa_split_energy_functional,
    crpa_split_mode,
    crpa_split_uses_active_cnp_reference,
    crpa_split_uses_hartree_delta_fock_projector,
    crpa_split_uses_projector,
    crpa_split_uses_remote_bare,
    crpa_hf_energy_components,
    half_reference_delta_like,
    physical_projector_from_delta,
    run_bare_split_full_hartree_fock,
    run_full_crpa_hartree_fock,
    select_active_cnp_reference_components,
    select_remote_reference_components,
    split_oda_parameter,
)

__all__ = [
    "AllBandBMSolution",
    "BandClassification",
    "CRPACoulombParams",
    "CRPAKGrid",
    "CRPAResult",
    "CRPAScreenedCoulomb",
    "DielectricResult",
    "active_lower_flat_projector_like",
    "apply_chi0_energy_mode",
    "apply_eq19_flat_remote_correction",
    "apply_hf_active_flat_basis",
    "build_q_shift_table",
    "build_bare_projected_interaction_components",
    "build_bare_projected_target_components",
    "build_bare_split_full_hf_kernel",
    "build_crpa_hartree_delta_fock_projector_components",
    "build_crpa_projected_interaction_components",
    "build_crpa_projected_interaction_hamiltonian",
    "build_crpa_projected_target_components",
    "build_crpa_projected_target_components_from_densities",
    "build_crpa_projected_target_hamiltonian",
    "build_fock_screened_overlap_blocks",
    "build_full_crpa_hf_kernel",
    "build_uniform_crpa_grid",
    "classify_flat_bands",
    "compute_constrained_chi0",
    "compute_constrained_chi0_by_subtraction",
    "compute_crpa",
    "compute_dielectric",
    "compute_flat_flat_chi0",
    "compute_full_chi0",
    "constrained_sum_identity_error",
    "crpa_active_density_from_delta",
    "crpa_hartree_delta_fock_projector_energy_components",
    "crpa_remote_bare_scale",
    "crpa_split_energy_functional",
    "crpa_split_mode",
    "crpa_split_uses_active_cnp_reference",
    "crpa_split_uses_hartree_delta_fock_projector",
    "crpa_split_uses_projector",
    "crpa_split_uses_remote_bare",
    "coulomb_potential_mev",
    "coulomb_potential_table_mev",
    "crpa_hf_energy_components",
    "half_reference_delta_like",
    "has_full_crpa_q_table",
    "load_crpa_result",
    "normalize_chi0_energy_mode",
    "physical_projector_from_delta",
    "read_all_band_bm_solution",
    "run_bare_split_full_hartree_fock",
    "run_full_crpa_hartree_fock",
    "select_active_cnp_reference_components",
    "select_remote_reference_components",
    "solve_all_band_bm_model",
    "split_oda_parameter",
    "validate_hf_compatible_crpa",
    "write_all_band_bm_solution",
    "write_all_epsilon_diagnostics",
    "write_crpa_epsilon_diagnostics_csv",
    "write_crpa_outputs",
]
