from __future__ import annotations

"""Compatibility facade for RnG/hBN projected Hartree-Fock helpers."""

from ._hf_shared import (
    RLG_HBN_BASIS_PERIODIC_GAUGE_PADDING,
    RLG_HBN_BASIS_PERIODIC_GAUGE_VERSION,
    RLG_HBN_FORM_FACTOR_CONVENTION_VERSION,
    VALLEY_SEQUENCE,
    compute_hf_energy,
    rlg_hbn_layer_component_groups,
)
from ._hf_reference import (
    active_band_indices_for_interaction,
    average_scheme_density_delta,
    rlg_hbn_average_reference_density,
    rlg_hbn_density_delta,
    rlg_hbn_filling_from_density,
    rlg_hbn_occupied_bands_per_k,
    rlg_hbn_occupied_state_count,
    rlg_hbn_projector_from_density,
    rlg_hbn_reference_density,
)
from ._hf_types import (
    RLGhBNGroundStateScan,
    RLGhBNHFPathResult,
    RLGhBNHartreeFockRun,
    RLGhBNHartreeFockState,
    RLGhBNInteractionComponents,
    RLGhBNLayerOverlapBlockSet,
    RLGhBNProjectedBasisData,
)
from ._hf_basis import (
    build_rlg_hbn_projected_basis,
    build_rlg_hbn_projected_basis_for_kvec,
    build_rlg_hbn_remote_average_hamiltonian,
)
from ._hf_interaction_path import (
    build_rlg_hbn_hf_interaction_hamiltonian,
    build_rlg_hbn_interaction_components,
    build_rlg_hbn_layer_overlap_blocks,
    build_rlg_hbn_layer_overlap_blocks_between,
    build_rlg_hbn_target_hamiltonian,
    calculate_layer_projected_overlap_between,
    diagonal_layer_overlap_blocks,
    evaluate_rlg_hbn_hf_path,
    interaction_shifts_for_cutoff,
)
from ._hf_runner import (
    build_rlg_hbn_density_from_hamiltonian,
    build_rlg_hbn_hf_problem,
    compute_rlg_hbn_oda_parameter,
    initialize_rlg_hbn_density,
    normalize_rlg_hbn_init_mode,
    rlg_hbn_flavor_occupation_counts_for_init_mode,
    rlg_hbn_gap_estimate,
    rlg_hbn_hermitian_residual,
    rlg_hbn_projector_idempotency_residual,
    run_rlg_hbn_hartree_fock,
    scan_rlg_hbn_ground_state,
)
from ._hf_reconstruction import (
    build_rlg_hbn_final_hf_eigensystem,
    expand_rlg_hbn_projected_micro_basis,
    reconstruct_rlg_hbn_projected_hf_micro_wavefunctions,
    rlg_hbn_projected_hf_active_index,
)
from .interaction import RLGhBNInteractionParams
from .model import RLGhBNModel

__all__ = [
    "RLGhBNGroundStateScan",
    "RLGhBNHFPathResult",
    "RLGhBNHartreeFockRun",
    "RLGhBNHartreeFockState",
    "RLGhBNInteractionComponents",
    "RLGhBNInteractionParams",
    "RLGhBNLayerOverlapBlockSet",
    "RLGhBNModel",
    "RLGhBNProjectedBasisData",
    "RLG_HBN_BASIS_PERIODIC_GAUGE_PADDING",
    "RLG_HBN_BASIS_PERIODIC_GAUGE_VERSION",
    "RLG_HBN_FORM_FACTOR_CONVENTION_VERSION",
    "VALLEY_SEQUENCE",
    "active_band_indices_for_interaction",
    "average_scheme_density_delta",
    "build_rlg_hbn_density_from_hamiltonian",
    "build_rlg_hbn_hf_interaction_hamiltonian",
    "build_rlg_hbn_hf_problem",
    "build_rlg_hbn_interaction_components",
    "build_rlg_hbn_layer_overlap_blocks",
    "build_rlg_hbn_layer_overlap_blocks_between",
    "build_rlg_hbn_projected_basis",
    "build_rlg_hbn_final_hf_eigensystem",
    "build_rlg_hbn_projected_basis_for_kvec",
    "build_rlg_hbn_remote_average_hamiltonian",
    "build_rlg_hbn_target_hamiltonian",
    "calculate_layer_projected_overlap_between",
    "compute_hf_energy",
    "compute_rlg_hbn_oda_parameter",
    "diagonal_layer_overlap_blocks",
    "evaluate_rlg_hbn_hf_path",
    "expand_rlg_hbn_projected_micro_basis",
    "initialize_rlg_hbn_density",
    "interaction_shifts_for_cutoff",
    "normalize_rlg_hbn_init_mode",
    "rlg_hbn_average_reference_density",
    "rlg_hbn_density_delta",
    "rlg_hbn_filling_from_density",
    "rlg_hbn_flavor_occupation_counts_for_init_mode",
    "rlg_hbn_gap_estimate",
    "rlg_hbn_hermitian_residual",
    "rlg_hbn_layer_component_groups",
    "rlg_hbn_occupied_bands_per_k",
    "rlg_hbn_occupied_state_count",
    "reconstruct_rlg_hbn_projected_hf_micro_wavefunctions",
    "rlg_hbn_projected_hf_active_index",
    "rlg_hbn_projector_from_density",
    "rlg_hbn_projector_idempotency_residual",
    "rlg_hbn_reference_density",
    "run_rlg_hbn_hartree_fock",
    "scan_rlg_hbn_ground_state",
]
