"""Unified Berry-geometry analysis framework.

Use :func:`compute_lattice_topology` for system-independent Berry connection,
Fukui-Hatsugai-Suzuki plaquette flux, and Chern-number calculations.  The only
system-specific inputs are the selected wavefunction columns, their index labels,
and optional boundary sewing transforms.
"""

from .core import (
    DirectBandGapReport,
    LatticeTopologyResult,
    LinkMethod,
    LinkVariables,
    SewingTransform,
    WavefunctionIndex,
    adjacent_direct_gap_reports,
    berry_curvature_from_links,
    chern_number_from_berry_curvature,
    compute_lattice_topology,
    compute_lattice_topology_for_state_groups,
    compute_link_variables,
    direct_band_gap_report,
    default_k_grid_frac,
    matrix_sewing_transform,
    normalize_state_indices,
    select_wavefunction_subspace,
    split_state_indices_by_direct_gaps,
    wavefunction_index_for_state_group,
)
from .quantum_geometry import (
    CoordinateSystem,
    NormalizedQuantumGeometryMaps,
    QuantumGeometryResult,
    brillouin_zone_area,
    compute_quantum_geometry,
    fubini_study_trace,
    infer_berry_sign_from_chern,
    integrated_fubini_study_metric,
    normalize_quantum_geometry_maps,
    normalized_chern_density,
    orthonormalize_wavefunction_frames,
    projector_qgt_central_difference,
    projector_qgt_forward_difference,
    qgt_to_metric_and_berry,
    reciprocal_vectors_to_derivative_transform,
    trace_condition_violation,
    transform_quantum_geometric_tensor,
)
from .system import (
    TopologyResult,
    compute_system_topology_from_eigenvectors,
    compute_system_topology_from_grid_result,
    compute_system_topology_on_grid,
    make_topology_adapter,
    topology_result_from_lattice_result,
)
from .wavefunction import (
    CanonicalWavefunctionGrid,
    WavefunctionLayout,
    canonicalize_wavefunction_grid,
    reconstruct_projected_micro_wavefunctions,
    reshape_flat_mesh_to_grid,
    wavefunction_index_from_state_labels,
)

__all__ = [
    "CanonicalWavefunctionGrid",
    "CoordinateSystem",
    "DirectBandGapReport",
    "LatticeTopologyResult",
    "LinkMethod",
    "LinkVariables",
    "NormalizedQuantumGeometryMaps",
    "QuantumGeometryResult",
    "SewingTransform",
    "TopologyResult",
    "WavefunctionIndex",
    "WavefunctionLayout",
    "adjacent_direct_gap_reports",
    "berry_curvature_from_links",
    "brillouin_zone_area",
    "canonicalize_wavefunction_grid",
    "chern_number_from_berry_curvature",
    "compute_lattice_topology",
    "compute_lattice_topology_for_state_groups",
    "compute_link_variables",
    "compute_quantum_geometry",
    "compute_system_topology_from_eigenvectors",
    "compute_system_topology_from_grid_result",
    "compute_system_topology_on_grid",
    "make_topology_adapter",
    "default_k_grid_frac",
    "direct_band_gap_report",
    "fubini_study_trace",
    "infer_berry_sign_from_chern",
    "integrated_fubini_study_metric",
    "matrix_sewing_transform",
    "normalize_quantum_geometry_maps",
    "normalize_state_indices",
    "normalized_chern_density",
    "orthonormalize_wavefunction_frames",
    "projector_qgt_central_difference",
    "projector_qgt_forward_difference",
    "qgt_to_metric_and_berry",
    "reciprocal_vectors_to_derivative_transform",
    "reconstruct_projected_micro_wavefunctions",
    "reshape_flat_mesh_to_grid",
    "select_wavefunction_subspace",
    "split_state_indices_by_direct_gaps",
    "topology_result_from_lattice_result",
    "trace_condition_violation",
    "transform_quantum_geometric_tensor",
    "wavefunction_index_for_state_group",
    "wavefunction_index_from_state_labels",
]
