from __future__ import annotations

from mean_field.systems.tdbg import projected_hf, projected_hf_interactions


def test_tdbg_projected_hf_interactions_split_preserves_legacy_facade() -> None:
    assert projected_hf.build_tdbg_total_overlap_blocks is projected_hf_interactions.build_tdbg_total_overlap_blocks
    assert projected_hf._local_lambda is projected_hf_interactions._local_lambda
    assert projected_hf.build_tdbg_onsite_hamiltonian is projected_hf_interactions.build_tdbg_onsite_hamiltonian
    assert projected_hf.graphene_area_over_moire_area is projected_hf_interactions.graphene_area_over_moire_area
    assert projected_hf._split_intersite_overlap_blocks is projected_hf_interactions._split_intersite_overlap_blocks
    assert projected_hf.build_tdbg_interaction_components is projected_hf_interactions.build_tdbg_interaction_components
    assert projected_hf.TDBGProjectedHFInteractionBuilder is projected_hf_interactions.TDBGProjectedHFInteractionBuilder
    assert projected_hf.build_tdbg_interaction_builder is projected_hf_interactions.build_tdbg_interaction_builder
    assert projected_hf._stored_inner_ev is projected_hf_interactions._stored_inner_ev
    assert projected_hf.tdbg_energy_components is projected_hf_interactions.tdbg_energy_components
