"""Twisted double bilayer graphene noninteracting model."""

from .bands import GridBandsResult, PathBandsResult, compute_bands_along_path, compute_bands_on_grid
from .hamiltonian import (
    build_bilayer_block,
    build_hamiltonian,
    build_site_block,
    diagonalize_hamiltonian,
    moire_coupling_matrix,
)
from .lattice import TDBGLattice, build_kpath_from_nodes, build_moire_k_grid, build_standard_kpath, build_tdbg_lattice
from .model import TDBGModel
from .params import TDBGParameters, delta_from_paper_ud, layer_potentials_from_delta, paper_ud_layer_potentials
from .hf import (
    TDBGActiveBandFlavorData,
    TDBGFlavorCandidateEnergy,
    TDBGInteractionSettings,
    TDBGOnsiteHubbardFormFactorSummary,
    TDBGProjectedHFConfig,
    TDBGProjectedHFData,
    TDBGProjectedHFResult,
    TDBGProjectedHFState,
    TDBGProjectedWindow,
    active_band_flavor_data_from_grid,
    build_tdbg_hf_target_hamiltonian,
    build_tdbg_projected_hf_data,
    build_tdbg_projected_hf_problem,
    evaluate_nu2_sp_vp_single_band_candidates,
    layer_sublattice_weights,
    run_tdbg_projected_hf,
    scan_tdbg_projected_hf_states,
    tdbg_density_from_hamiltonian,
    tdbg_delta_from_paper_ud_for_valley,
    tdbg_order_parameters,
    validate_tdbg_interaction_settings,
    validate_tdbg_projected_hf_config,
)
from .plot import TDBGPathPlotTrace, write_tdbg_path_band_plot
from .topology import TopologyResult, compute_topology_from_eigenvectors, compute_topology_from_grid_result, compute_topology_on_grid
from .validation import (
    ReferenceComparisonResult,
    ValidationCheck,
    ValidationReport,
    compare_against_pytwist_reference,
    validate_physics,
)

__all__ = [
    "GridBandsResult",
    "PathBandsResult",
    "ReferenceComparisonResult",
    "TDBGModel",
    "TDBGLattice",
    "TDBGParameters",
    "TDBGActiveBandFlavorData",
    "TDBGFlavorCandidateEnergy",
    "TDBGInteractionSettings",
    "TDBGOnsiteHubbardFormFactorSummary",
    "TDBGPathPlotTrace",
    "TDBGProjectedHFConfig",
    "TDBGProjectedHFData",
    "TDBGProjectedHFResult",
    "TDBGProjectedHFState",
    "TDBGProjectedWindow",
    "TopologyResult",
    "ValidationCheck",
    "ValidationReport",
    "build_bilayer_block",
    "build_hamiltonian",
    "build_kpath_from_nodes",
    "build_moire_k_grid",
    "build_site_block",
    "build_standard_kpath",
    "build_tdbg_hf_target_hamiltonian",
    "build_tdbg_lattice",
    "build_tdbg_projected_hf_data",
    "build_tdbg_projected_hf_problem",
    "active_band_flavor_data_from_grid",
    "compare_against_pytwist_reference",
    "delta_from_paper_ud",
    "compute_bands_along_path",
    "compute_bands_on_grid",
    "compute_topology_from_eigenvectors",
    "compute_topology_from_grid_result",
    "compute_topology_on_grid",
    "diagonalize_hamiltonian",
    "evaluate_nu2_sp_vp_single_band_candidates",
    "layer_potentials_from_delta",
    "layer_sublattice_weights",
    "moire_coupling_matrix",
    "paper_ud_layer_potentials",
    "run_tdbg_projected_hf",
    "scan_tdbg_projected_hf_states",
    "tdbg_density_from_hamiltonian",
    "tdbg_delta_from_paper_ud_for_valley",
    "tdbg_order_parameters",
    "validate_physics",
    "validate_tdbg_interaction_settings",
    "validate_tdbg_projected_hf_config",
    "write_tdbg_path_band_plot",
]
