"""Differential layered-Poisson Hartree operators for projected Kane4 states.

The operator acts on ``D=P-P0`` and therefore adds only the electrostatic
response missing from the frozen normal-state Kane-Poisson potential. Periodic
and open-zero-field boundaries are controlled scaffold closures; neither is a
replacement for the unknown device fixed-gate functional.
"""

from __future__ import annotations

from dataclasses import dataclass
import hashlib

import numpy as np

from .layered_green import (
    layered_electrostatics_fingerprint,
    open_layered_green_on_mesh_mev_nm2,
    open_layered_poisson_electron_energy_mev,
    one_sided_gated_layered_green_on_mesh_mev_nm2,
    one_sided_gated_poisson_electron_energy_mev,
)
from .projected_model import Kane4Bundle, ProjectedFockOperator


COULOMB_MEV_NM = 1439.96448


@dataclass(frozen=True)
class _ElectrostaticsAttestation:
    specification_fingerprint: str
    bundle_fingerprint: str
    fock_operator_sha256: str


def wafer_b_dielectric_profile(z_nm: np.ndarray) -> np.ndarray:
    """Supplementary-Table-1 dielectric profile for the modeled Wafer-B stack."""

    z = np.asarray(z_nm, dtype=float)
    epsilon = np.full_like(z, 14.4)
    epsilon[(z >= -9.75) & (z < 1.75)] = 14.55
    epsilon[(z >= 1.75) & (z < 9.75)] = 15.69
    return epsilon


def periodic_poisson_electron_energy_mev(
    z_nm: np.ndarray,
    electron_density_delta_nm3: np.ndarray,
    epsilon_r: np.ndarray,
) -> np.ndarray:
    """Solve ``d_z(epsilon d_z U)=-4*pi*C*delta_n`` with periodic BC."""

    z = np.asarray(z_nm, dtype=float)
    density = np.asarray(electron_density_delta_nm3, dtype=float)
    epsilon = np.asarray(epsilon_r, dtype=float)
    if not (z.shape == density.shape == epsilon.shape) or z.ndim != 1 or z.size < 4:
        raise ValueError("z, density, and epsilon must be matching one-dimensional arrays")
    spacing = np.diff(z)
    if not np.allclose(spacing, spacing[0], rtol=0.0, atol=1e-12):
        raise ValueError("periodic Poisson requires a uniform z grid")
    if not all(np.all(np.isfinite(array)) for array in (z, density, epsilon)) or np.any(epsilon <= 0.0):
        raise ValueError("periodic Poisson inputs must be finite with positive epsilon")
    dz = float(spacing[0])
    integrated = float(np.sum(density) * dz)
    scale = max(1.0, float(np.sum(np.abs(density)) * dz))
    if abs(integrated) > 1e-9 * scale:
        raise ValueError(f"periodic Poisson source is not neutral: {integrated:.3e} nm^-2")
    density = density - np.mean(density)

    n = z.size
    matrix = np.zeros((n, n), dtype=float)
    epsilon_plus = 2.0 * epsilon * np.roll(epsilon, -1) / (epsilon + np.roll(epsilon, -1))
    epsilon_minus = np.roll(epsilon_plus, 1)
    for i in range(n):
        matrix[i, i] = -(epsilon_plus[i] + epsilon_minus[i]) / dz**2
        matrix[i, (i + 1) % n] = epsilon_plus[i] / dz**2
        matrix[i, (i - 1) % n] = epsilon_minus[i] / dz**2
    source = -4.0 * np.pi * COULOMB_MEV_NM * density
    matrix[-1, :] = 1.0 / n
    source[-1] = 0.0
    potential = np.linalg.solve(matrix, source)
    potential -= np.mean(potential)
    return potential


def diagonal_local_density_vertices(micro_wavefunctions: np.ndarray) -> np.ndarray:
    """Return ``Lambda[k,z,a,b]=Phi[k,z]^dagger Phi[k,z]``."""

    phi = np.asarray(micro_wavefunctions, dtype=np.complex128)
    if phi.ndim != 4:
        raise ValueError("micro_wavefunctions must have shape (nk, nz, nmicro, n)")
    return np.einsum("kzma,kzmb->kzab", phi.conj(), phi, optimize=True)


@dataclass(frozen=True)
class ReferenceSubtractedChargeDensity:
    """UV-safe electron-number change generated by ``D=P-P0``.

    The physical charge-density change is ``-e * electron_density_delta``.
    No decomposition into electron and hole quasiparticles is required.
    """

    electron_density_delta_nm3: np.ndarray
    active_number_change_nm2: float
    integrated_profile_nm2: float
    sum_rule_error_nm2: float


def _reference_subtracted_charge_from_vertices(
    density_delta: np.ndarray,
    local_vertices: np.ndarray,
    k_weights_nm2: np.ndarray,
    z_weights_nm: np.ndarray,
) -> ReferenceSubtractedChargeDensity:
    density = np.asarray(density_delta, dtype=np.complex128)
    local = np.asarray(local_vertices, dtype=np.complex128)
    wk = np.asarray(k_weights_nm2, dtype=float)
    wz = np.asarray(z_weights_nm, dtype=float)
    if local.ndim != 4:
        raise ValueError("local_vertices must have shape (nk,nz,n,n)")
    nk, nz, n, n2 = local.shape
    if n != n2 or density.shape != (n, n, nk) or wk.shape != (nk,) or wz.shape != (nz,):
        raise ValueError("reference-subtracted charge arrays have incompatible shapes")
    hermiticity_error = float(np.max(np.abs(density - np.swapaxes(density.conj(), 0, 1))))
    if hermiticity_error > 1e-8:
        raise ValueError(f"density_delta is not Hermitian: error={hermiticity_error:.3e}")
    profile = np.einsum("k,kzab,bak->z", wk, local, density, optimize=True)
    if not np.all(np.isfinite(profile)) or float(np.max(np.abs(profile.imag))) > 1e-9:
        raise ValueError("reference-subtracted density profile is nonfinite or complex")
    profile_real = np.asarray(profile.real, dtype=float)
    active_number = float(np.einsum("k,aak->", wk, density, optimize=True).real)
    integrated = float(np.dot(wz, profile_real))
    return ReferenceSubtractedChargeDensity(
        electron_density_delta_nm3=profile_real,
        active_number_change_nm2=active_number,
        integrated_profile_nm2=integrated,
        sum_rule_error_nm2=integrated - active_number,
    )


def reference_subtracted_charge_density(
    bundle: Kane4Bundle,
    density_delta: np.ndarray,
) -> ReferenceSubtractedChargeDensity:
    """Project ``D=P-P0`` to real space and verify its number sum rule."""

    bundle.validate()
    result = _reference_subtracted_charge_from_vertices(
        density_delta,
        diagonal_local_density_vertices(bundle.micro_wavefunctions),
        bundle.weights_nm2,
        bundle.z_weights_nm,
    )
    scale = max(1.0, abs(result.active_number_change_nm2), abs(result.integrated_profile_nm2))
    if abs(result.sum_rule_error_nm2) > 1e-9 * scale:
        raise ValueError(
            "projected reference-subtracted charge violates the active-number sum rule: "
            f"error={result.sum_rule_error_nm2:.3e} nm^-2"
        )
    return result


@dataclass(frozen=True)
class ProjectedHartreeOperator:
    local_vertices: np.ndarray
    k_weights_nm2: np.ndarray
    z_nm: np.ndarray
    z_weights_nm: np.ndarray
    epsilon_r: np.ndarray
    bundle_fingerprint: str
    boundary_condition: str = "periodic_zero_mean"
    electrostatics_fingerprint: str | None = None
    electrostatics_token: object | None = None

    def __post_init__(self) -> None:
        local = np.array(self.local_vertices, dtype=np.complex128, copy=True)
        wk = np.array(self.k_weights_nm2, dtype=float, copy=True)
        z = np.array(self.z_nm, dtype=float, copy=True)
        wz = np.array(self.z_weights_nm, dtype=float, copy=True)
        epsilon = np.array(self.epsilon_r, dtype=float, copy=True)
        for name, array in (
            ("local_vertices", local),
            ("k_weights_nm2", wk),
            ("z_nm", z),
            ("z_weights_nm", wz),
            ("epsilon_r", epsilon),
        ):
            array.setflags(write=False)
            object.__setattr__(self, name, array)
        if local.ndim != 4 or local.shape[0] != wk.size or local.shape[1] != z.size:
            raise ValueError("Hartree local vertices have incompatible shapes")
        if wz.shape != z.shape or epsilon.shape != z.shape:
            raise ValueError("Hartree z arrays have incompatible shapes")
        spacing = np.diff(z)
        if spacing.size == 0 or not np.allclose(spacing, spacing[0], rtol=0.0, atol=1e-12):
            raise ValueError("layered Hartree requires a uniform z grid")
        if not np.allclose(wz, spacing[0], rtol=0.0, atol=1e-12):
            raise ValueError("layered Hartree requires z_weights_nm equal to the uniform dz")
        if not all(np.all(np.isfinite(array)) for array in (local, wk, z, wz, epsilon)):
            raise ValueError("Hartree operator arrays must be finite")
        if np.any(wk <= 0.0) or np.any(wz <= 0.0) or np.any(epsilon <= 0.0):
            raise ValueError("Hartree weights and dielectric profile must be positive")
        supported_boundaries = {
            "periodic_zero_mean",
            "open_zero_field",
            "one_sided_gate_left",
            "one_sided_gate_right",
        }
        if self.boundary_condition not in supported_boundaries:
            raise ValueError("unsupported Hartree boundary condition")
        if not self.bundle_fingerprint:
            raise ValueError("missing Hartree bundle fingerprint")
        if self.electrostatics_fingerprint is not None and (
            len(self.electrostatics_fingerprint) != 64
            or any(character not in "0123456789abcdef" for character in self.electrostatics_fingerprint)
        ):
            raise ValueError("Hartree electrostatics_fingerprint must be a lowercase SHA-256 hex digest")
        if self.electrostatics_token is not None and self.electrostatics_fingerprint is None:
            raise ValueError("a Hartree electrostatics token requires a fingerprint")

    @classmethod
    def from_bundle(
        cls,
        bundle: Kane4Bundle,
        epsilon_r: np.ndarray,
        *,
        boundary_condition: str = "periodic_zero_mean",
        _electrostatics_token: object | None = None,
    ) -> "ProjectedHartreeOperator":
        bundle.validate()
        epsilon = np.asarray(epsilon_r, dtype=float)
        electrostatics_fingerprint = layered_electrostatics_fingerprint(
            bundle.z_nm,
            bundle.z_weights_nm,
            epsilon,
            boundary_family=boundary_condition,
        )
        return cls(
            local_vertices=diagonal_local_density_vertices(bundle.micro_wavefunctions),
            k_weights_nm2=np.asarray(bundle.weights_nm2, dtype=float),
            z_nm=np.asarray(bundle.z_nm, dtype=float),
            z_weights_nm=np.asarray(bundle.z_weights_nm, dtype=float),
            epsilon_r=epsilon,
            bundle_fingerprint=bundle.fingerprint(),
            boundary_condition=boundary_condition,
            electrostatics_fingerprint=electrostatics_fingerprint,
            electrostatics_token=_electrostatics_token,
        )

    def validate_against_bundle(self, bundle: Kane4Bundle, *, atol: float = 1e-10) -> None:
        bundle.validate()
        if self.bundle_fingerprint != bundle.fingerprint():
            raise ValueError("Hartree operator and bundle fingerprints do not match")
        expected = diagonal_local_density_vertices(bundle.micro_wavefunctions)
        if not np.allclose(self.local_vertices, expected, rtol=1e-10, atol=atol):
            raise ValueError("Hartree vertices do not come from the supplied bundle")
        if not np.allclose(self.k_weights_nm2, bundle.weights_nm2, rtol=0.0, atol=atol):
            raise ValueError("Hartree k weights do not come from the supplied bundle")
        if not np.allclose(self.z_nm, bundle.z_nm, rtol=0.0, atol=atol):
            raise ValueError("Hartree z grid does not come from the supplied bundle")
        if not np.allclose(self.z_weights_nm, bundle.z_weights_nm, rtol=0.0, atol=atol):
            raise ValueError("Hartree z weights do not come from the supplied bundle")

    def charge_density(self, density_delta: np.ndarray) -> ReferenceSubtractedChargeDensity:
        result = _reference_subtracted_charge_from_vertices(
            density_delta,
            self.local_vertices,
            self.k_weights_nm2,
            self.z_weights_nm,
        )
        scale = max(1.0, abs(result.active_number_change_nm2), abs(result.integrated_profile_nm2))
        if abs(result.sum_rule_error_nm2) > 1e-9 * scale:
            raise ValueError(
                "Hartree density violates the active-number sum rule: "
                f"error={result.sum_rule_error_nm2:.3e} nm^-2"
            )
        return result

    def density_profile_nm3(self, density_delta: np.ndarray) -> np.ndarray:
        return self.charge_density(density_delta).electron_density_delta_nm3

    def components(self, density_delta: np.ndarray) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
        profile = self.density_profile_nm3(density_delta)
        if self.boundary_condition == "periodic_zero_mean":
            potential = periodic_poisson_electron_energy_mev(self.z_nm, profile, self.epsilon_r)
        elif self.boundary_condition == "open_zero_field":
            potential = open_layered_poisson_electron_energy_mev(
                self.z_nm,
                profile,
                self.epsilon_r,
            )
        elif self.boundary_condition in {"one_sided_gate_left", "one_sided_gate_right"}:
            potential = one_sided_gated_poisson_electron_energy_mev(
                self.z_nm,
                profile,
                self.epsilon_r,
                gate_side=self.boundary_condition.removeprefix("one_sided_gate_"),
                gate_electron_energy_mev=0.0,
            )
        else:  # guarded by __post_init__
            raise RuntimeError("unreachable Hartree boundary condition")
        sigma = np.einsum(
            "kzab,z,z->abk",
            self.local_vertices,
            potential,
            self.z_weights_nm,
            optimize=True,
        )
        error = float(np.max(np.abs(sigma - np.swapaxes(sigma.conj(), 0, 1))))
        if error > 1e-8:
            raise ValueError(f"projected Hartree self-energy is not Hermitian: {error:.3e}")
        return np.asarray(sigma, dtype=np.complex128), profile, potential

    def __call__(self, density_delta: np.ndarray) -> np.ndarray:
        return self.components(density_delta)[0]

    def energy_density_mev_nm2(self, density_delta: np.ndarray) -> float:
        sigma = self(density_delta)
        value = 0.5 * np.einsum(
            "k,abk,bak->",
            self.k_weights_nm2,
            sigma,
            density_delta,
            optimize=True,
        )
        if abs(value.imag) > 1e-9:
            raise ValueError("Hartree energy is not real")
        return float(value.real)

    def fingerprint(self) -> str:
        digest = hashlib.sha256()
        digest.update(self.bundle_fingerprint.encode())
        digest.update(self.boundary_condition.encode())
        digest.update((self.electrostatics_fingerprint or "unspecified").encode())
        for array in (
            np.asarray(self.local_vertices, dtype=np.complex128),
            np.asarray(self.k_weights_nm2, dtype=np.float64),
            np.asarray(self.z_nm, dtype=np.float64),
            np.asarray(self.z_weights_nm, dtype=np.float64),
            np.asarray(self.epsilon_r, dtype=np.float64),
        ):
            contiguous = np.ascontiguousarray(array)
            digest.update(str(contiguous.dtype).encode())
            digest.update(str(contiguous.shape).encode())
            digest.update(contiguous.view(np.uint8))
        return digest.hexdigest()


@dataclass(frozen=True)
class ProjectedHartreeFockOperator:
    hartree: ProjectedHartreeOperator
    fock: ProjectedFockOperator
    allow_mixed_electrostatics: bool = False

    def __post_init__(self) -> None:
        if self.hartree.bundle_fingerprint != self.fock.bundle_fingerprint:
            raise ValueError("Hartree and Fock operators use different bundles")
        if (
            not self._has_valid_common_attestation()
            and not self._has_zero_fock_action()
            and not self.allow_mixed_electrostatics
        ):
            raise ValueError(
                "Hartree and Fock do not share one builder-attested electrostatics specification; "
                "set allow_mixed_electrostatics=True only for an explicitly labeled scaffold"
            )

    def _has_zero_fock_action(self) -> bool:
        zero_green = float(np.max(np.abs(self.fock.green_mev_nm2))) == 0.0
        zero_tensor = (
            self.fock.exchange_tensor_mev_nm2 is None
            or float(np.max(np.abs(self.fock.exchange_tensor_mev_nm2))) == 0.0
        )
        return zero_green and zero_tensor

    def _has_valid_common_attestation(self) -> bool:
        hartree_spec = self.hartree.electrostatics_fingerprint
        fock_spec = self.fock.electrostatics_fingerprint
        attestation = self.hartree.electrostatics_token
        derived_hartree_spec = layered_electrostatics_fingerprint(
            self.hartree.z_nm,
            self.hartree.z_weights_nm,
            self.hartree.epsilon_r,
            boundary_family=self.hartree.boundary_condition,
        )
        return bool(
            isinstance(attestation, _ElectrostaticsAttestation)
            and attestation is self.fock.electrostatics_token
            and hartree_spec is not None
            and hartree_spec == fock_spec == derived_hartree_spec
            and attestation.specification_fingerprint == hartree_spec
            and attestation.bundle_fingerprint == self.hartree.bundle_fingerprint
            and attestation.fock_operator_sha256
            == self.fock.action_storage_fingerprint()
            and np.array_equal(self.hartree.k_weights_nm2, self.fock.k_weights_nm2)
            and np.array_equal(self.hartree.z_weights_nm, self.fock.z_weights_nm)
        )

    @classmethod
    def from_bundle_open_layered(
        cls,
        bundle: Kane4Bundle,
        epsilon_r: np.ndarray,
        *,
        epsilon_left: float | None = None,
        epsilon_right: float | None = None,
        self_cell_quadrature_order: int = 12,
        precompute_exchange_tensor: bool = False,
    ) -> "ProjectedHartreeFockOperator":
        """Use one open layered dielectric problem for Hartree and Fock.

        This removes the Phase-1 mixed periodic/uniform kernel, but it remains
        an ungated zero-exterior-field scaffold rather than a fixed-gate device
        functional.
        """

        bundle.validate()
        epsilon = np.array(epsilon_r, dtype=float, copy=True)
        epsilon.setflags(write=False)
        electrostatics_fingerprint = layered_electrostatics_fingerprint(
            bundle.z_nm,
            bundle.z_weights_nm,
            epsilon,
            boundary_family="open_zero_field",
            epsilon_left=epsilon_left,
            epsilon_right=epsilon_right,
        )
        green = open_layered_green_on_mesh_mev_nm2(
            bundle.k_cart_nm_inv,
            bundle.weights_nm2,
            bundle.z_nm,
            epsilon,
            epsilon_left=epsilon_left,
            epsilon_right=epsilon_right,
            self_cell_quadrature_order=self_cell_quadrature_order,
        )
        green.setflags(write=False)
        fock = ProjectedFockOperator.from_bundle(
            bundle,
            green,
            self_cell_description=(
                "open layered dielectric, discrete transparent z boundaries, "
                f"equal-area circular q self cell, Gauss-Legendre order "
                f"{int(self_cell_quadrature_order)}; no metallic gates"
            ),
            precompute_exchange_tensor=precompute_exchange_tensor,
            electrostatics_fingerprint=electrostatics_fingerprint,
            _take_green_ownership=True,
        )
        electrostatics_token = _ElectrostaticsAttestation(
            specification_fingerprint=electrostatics_fingerprint,
            bundle_fingerprint=bundle.fingerprint(),
            fock_operator_sha256=fock.action_storage_fingerprint(),
        )
        object.__setattr__(fock, "electrostatics_token", electrostatics_token)
        hartree = ProjectedHartreeOperator.from_bundle(
            bundle,
            epsilon,
            boundary_condition="open_zero_field",
            _electrostatics_token=electrostatics_token,
        )
        return cls(hartree=hartree, fock=fock)

    @classmethod
    def from_bundle_one_sided_gated(
        cls,
        bundle: Kane4Bundle,
        epsilon_r: np.ndarray,
        *,
        gate_side: str,
        epsilon_open: float | None = None,
        self_cell_quadrature_order: int = 12,
        precompute_exchange_tensor: bool = False,
    ) -> "ProjectedHartreeFockOperator":
        """Use one metal-gate/open layered response problem for Hartree and Fock.

        The response Green function has a homogeneous Dirichlet condition at a
        metal plane half a z-grid step beyond ``gate_side`` and a transparent
        boundary on the opposite side. The nonzero external gate potential must
        already be included in the source ``H0``; this builder supplies only the
        interaction response to ``D=P-P0``.
        """

        side = str(gate_side).lower()
        if side not in {"left", "right"}:
            raise ValueError("gate_side must be 'left' or 'right'")
        bundle.validate()
        epsilon = np.array(epsilon_r, dtype=float, copy=True)
        epsilon.setflags(write=False)
        boundary = f"one_sided_gate_{side}"
        fingerprint_kwargs = (
            {"epsilon_right": epsilon_open}
            if side == "left"
            else {"epsilon_left": epsilon_open}
        )
        electrostatics_fingerprint = layered_electrostatics_fingerprint(
            bundle.z_nm,
            bundle.z_weights_nm,
            epsilon,
            boundary_family=boundary,
            **fingerprint_kwargs,
        )
        green = one_sided_gated_layered_green_on_mesh_mev_nm2(
            bundle.k_cart_nm_inv,
            bundle.weights_nm2,
            bundle.z_nm,
            epsilon,
            gate_side=side,
            epsilon_open=epsilon_open,
            self_cell_quadrature_order=self_cell_quadrature_order,
        )
        green.setflags(write=False)
        gate_plane = (
            float(bundle.z_nm[0] - 0.5 * bundle.z_weights_nm[0])
            if side == "left"
            else float(bundle.z_nm[-1] + 0.5 * bundle.z_weights_nm[-1])
        )
        fock = ProjectedFockOperator.from_bundle(
            bundle,
            green,
            self_cell_description=(
                f"one-sided metal gate at {side} z boundary ({gate_plane:.12g} nm), "
                "opposite discrete-transparent open boundary, equal-area circular q "
                f"self cell, Gauss-Legendre order {int(self_cell_quadrature_order)}"
            ),
            precompute_exchange_tensor=precompute_exchange_tensor,
            electrostatics_fingerprint=electrostatics_fingerprint,
            _take_green_ownership=True,
        )
        electrostatics_token = _ElectrostaticsAttestation(
            specification_fingerprint=electrostatics_fingerprint,
            bundle_fingerprint=bundle.fingerprint(),
            fock_operator_sha256=fock.action_storage_fingerprint(),
        )
        object.__setattr__(fock, "electrostatics_token", electrostatics_token)
        hartree = ProjectedHartreeOperator.from_bundle(
            bundle,
            epsilon,
            boundary_condition=boundary,
            _electrostatics_token=electrostatics_token,
        )
        return cls(hartree=hartree, fock=fock)

    @property
    def bundle_fingerprint(self) -> str:
        if self.hartree.bundle_fingerprint != self.fock.bundle_fingerprint:
            raise ValueError("Hartree and Fock operators use different bundles")
        return self.hartree.bundle_fingerprint

    def validate_against_bundle(self, bundle: Kane4Bundle) -> None:
        self.hartree.validate_against_bundle(bundle)
        self.fock.validate_against_bundle(bundle)
        if (
            not self.allow_mixed_electrostatics
            and not self._has_zero_fock_action()
            and not self._has_valid_common_attestation()
        ):
            raise ValueError("Hartree/Fock electrostatics attestation is no longer valid")

    def components(self, density_delta: np.ndarray) -> tuple[np.ndarray, np.ndarray]:
        return self.hartree(density_delta), self.fock(density_delta)

    def __call__(self, density_delta: np.ndarray) -> np.ndarray:
        sigma_h, sigma_f = self.components(density_delta)
        return sigma_h + sigma_f

    def fingerprint(self) -> str:
        digest = hashlib.sha256()
        digest.update(self.bundle_fingerprint.encode())
        digest.update(self.hartree.fingerprint().encode())
        digest.update(self.fock.fingerprint().encode())
        digest.update(str(bool(self.allow_mixed_electrostatics)).encode())
        return digest.hexdigest()
