"""ABC-trilayer system adapters.

The Vituri projected vertex is authority-limited: it is derived from the
projected Hamiltonian rather than copied from literal Eq. C3, which is
internally inconsistent with its stated antisymmetry.  The fixed derivation
source is the pinned arXiv-v1 ``SM.tex``; the separate published-PRB evidence
is pinned to PDF SHA256
``2226e17ed95bd867607787b47343fe5fc77f2c30557023e349d86e55159c0765``.
The package does not claim a paper phase gauge or production/paper numerical
parity for that layer.  The local Vituri scalar-Hessian adapter maps the
derived vertex to paper C9.  Its separate signed-q adapter assembles four
independent local A/B lanes into the core typed generic-q classes without
repair, but remains diagnostic-only: diagonal-HF stationarity, real
mesh/area/q0/UV/CDW authority, and production/executable readiness are not
established.  The restricted finite-orbital scalar oracle independently
constructs the exact local-conserving vertex tensor on
``assembly.orbital_id_map``, a Wick scalar, and a fixed-Ne bitstring
Hamiltonian.  It compares all four actual C9 lanes and uses the generic
``core/hf`` scalar certificate, but permanently retains
``restricted_finite_orbital_algebra_oracle_only`` authority and never mutates
the original sector authority.  The separate half-metal HF preflight validates provider-owned geometry,
ensemble, SCF, shared-functional, and attested-source receipts.  Its only
positive aggregate result is ``receipt_set_complete``; provider metadata is
``provider_metadata_attested`` while scientific execution remains explicitly
false.  The separate array-only replay adapter can load and verify canonical
saved arrays and base-mesh source structure; SCF trajectory, branch-table,
pocket-refinement, E->F->H functional-chain, and paper-reproduction replay
remain explicit NO-GO boundaries for that array-only receipt.  The separate functional replay executes only detached, hash-bound local
affine E->F and independent signed-block F->dF probes.  Its successful
``local_registered_functional_probes_replayed=True`` has local-only scope and
does not verify a global functional chain, SCF trajectories, branch tables,
pocket refinement, scientific execution, or paper reproduction.  The separate
uninterrupted SCF replay executes every attested seed exactly once through the
baseline generic ``HartreeFockProblem`` entrypoint.  Under its explicit
``trusted_live_provider_distinct_archive_object`` evidence model, a distinct
archive-authority object supplies the detached trajectory archive before the
live provider may build states/problems.  This prevents accidental same-object
coupling only: a trusted same-class/same-code provider could still read or copy
archive data into unmanifested state, so archive-data independence,
hostile-provider resistance, and independent live-dependency pinning remain
false.  Positive fields report deterministic parity only.  It is not a restart
replay: HEAD has no continuation API and hides ``cached_interaction_h``.  The
separate frozen-source pocket-refinement replay requires the factory array
receipt plus the exact SCF approval and its factory receipt, reconstructs all
derivable approval/provider/authority identities before delegation, loads a
detached archive before one trusted live evaluation, and recomputes
strict occupations, no-wrap 4/8-neighbor topology, and a discrete threshold
margin.  Its evidence model does not establish archive/live independence, a
real Vituri artifact, refined SCF/fixed density, continuum or refinement
stability, ground-state/paper claims, or TDHF readiness.
"""

from .vituri2024_interaction import (
    FORM_FACTOR_GAUGE_LABEL,
    F_tau,
    InteractionAuthorityKind,
    PAPER_EPSILON,
    PAPER_Q_TF_INVERSE_ANGSTROM,
    PAPER_Q_TF_PER_A0,
    Q0Evaluation,
    V0,
    VTF,
    Vituri2024DensityFormFactorReceipt,
    Vituri2024InteractionBinding,
    Vituri2024InteractionChoiceReceipt,
    Vituri2024LocalBandGapInfo,
    Vituri2024StateOverlapInvariant,
    bind_vituri2024_interaction,
    state_overlap_invariant,
    third_band_density_form_factor,
    v0,
    v_tf,
    vituri2024_v0,
    vituri2024_vtf,
    vtf,
)
from .vituri2024_rpa import (
    DIAGONAL_HF_SOURCE_PROVIDER_STATUS,
    FINITE_AREA_PROVIDER_STATUS,
    RPA_AREA_UNITS,
    RPA_A_ELEMENT_EQUATION,
    RPA_B_ELEMENT_EQUATION,
    RPA_ELEMENT_AUTHORITY,
    RPA_ELEMENT_NO_GO_LIMITS,
    RPA_ELEMENT_UNITS,
    RPA_VERTEX_UNITS,
    SCALAR_HESSIAN_EQUATION,
    RPAElementKind,
    Vituri2024DiagonalHFTransitionReceipt,
    Vituri2024FiniteAreaReceipt,
    Vituri2024RPAElementReceipt,
    vituri2024_rpa_a_element,
    vituri2024_rpa_b_element,
)
from .vituri2024_tdhf import (
    VITURI2024_TDHF_ASSEMBLY_AUTHORITY,
    VITURI2024_TDHF_NO_GO_LIMITS,
    VITURI2024_TDHF_Q_PROVENANCE,
    VITURI2024_TDHF_RESPONSE_SCOPE,
    SignedLane,
    Vituri2024SignedQPair,
    Vituri2024SignedQTransitionInventoryPair,
    Vituri2024TDHFAssemblyContext,
    Vituri2024TDHFSignedQAssemblyReceipt,
    Vituri2024TransitionInventory,
    assemble_vituri2024_tdhf_signed_q,
    vituri2024_tdhf_interaction_fingerprint,
)
from .vituri2024_tdhf_scalar import (
    VITURI2024_SCALAR_BLOCKERS,
    VITURI2024_SCALAR_READINESS_AUTHORITY,
    VITURI2024_SCALAR_READINESS_LOCKED_STRUCTURE_THRESHOLD,
    VITURI2024_SCALAR_STATIC_HESSIAN_AUTHORITY,
    Vituri2024TDHFAssemblyReceipt,
    Vituri2024TDHFScalarReadinessReceipt,
    Vituri2024TDHFTransitionSourceBinding,
    build_vituri2024_tdhf_scalar_factory_readiness,
    build_vituri2024_tdhf_scalar_readiness,
)
from .vituri2024_tdhf_restricted_scalar import (
    VITURI2024_RESTRICTED_SCALAR_ALGEBRA_ABSOLUTE_TOLERANCE,
    VITURI2024_RESTRICTED_SCALAR_ALGEBRA_RELATIVE_TOLERANCE,
    VITURI2024_RESTRICTED_SCALAR_AUTHORITY,
    VITURI2024_RESTRICTED_SCALAR_MAX_ORBITALS,
    VITURI2024_RESTRICTED_SCALAR_WICK_ABSOLUTE_TOLERANCE,
    VITURI2024_RESTRICTED_SCALAR_WICK_RELATIVE_TOLERANCE,
    Vituri2024RestrictedScalarDFColumnEvidence,
    Vituri2024RestrictedScalarOrbitalCrosswalk,
    Vituri2024RestrictedScalarResiduals,
    Vituri2024RestrictedScalarVertexBinding,
    Vituri2024TDHFRestrictedScalarApproval,
    Vituri2024TDHFRestrictedScalarReceipt,
    certify_vituri2024_tdhf_restricted_scalar,
    make_vituri2024_tdhf_restricted_scalar_approval,
)
from .vituri2024_hf_preflight import (
    FINITE_Q_HESSIAN_NORMALIZATION,
    FIXED_DENSITY_DIRECTION_CONVENTION,
    FOCK_FIRST_DERIVATIVE_NORMALIZATION,
    FOCK_OUTPUT_CONVENTION,
    STORED_DENSITY_PAIRING,
    VITURI2024_HALF_METAL_HF_SCOPE,
    VITURI2024_MAIN_TEX_SHA256,
    Vituri2024AttestedHalfMetalSourceArrays,
    Vituri2024AttestedHalfMetalSourceReceipt,
    Vituri2024BranchEnergyReceipt,
    Vituri2024FiniteDifferenceEvidenceReceipt,
    Vituri2024FunctionalComponentReceipt,
    Vituri2024HFEnsembleReceipt,
    Vituri2024HFGeometryReceipt,
    Vituri2024HFReceiptSetStatus,
    Vituri2024HFSCFPolicyReceipt,
    Vituri2024HalfMetalHFProviderBinding,
    Vituri2024HalfMetalHFProviderProtocol,
    Vituri2024HalfMetalHFSpec,
    Vituri2024HalfMetalPaperTarget,
    Vituri2024MetallicityEvidenceReceipt,
    Vituri2024ProviderMetadataAttestedStatus,
    Vituri2024SCFCallbackReceipt,
    Vituri2024SCFSeedReceipt,
    Vituri2024SharedFunctionalReceipt,
    Vituri2024ValleyPocketEvidenceReceipt,
)
from .vituri2024_hf_functional_replay import (
    AFFINE_ANCHOR_LABELS,
    DIRECT_DISPLACED_FOCK_CONSTRUCTION,
    FUNCTIONAL_REPLAY_ABI_FINGERPRINT,
    FUNCTIONAL_REPLAY_PAYLOAD_SCHEMA_FINGERPRINT,
    FUNCTIONAL_REPLAY_PROVIDER_METADATA_FIELDS,
    FUNCTIONAL_REPLAY_SCOPE,
    FUNCTIONAL_REPLAY_VERIFIER_IMPLEMENTATION_SCHEMA_FINGERPRINT,
    Q0_PROBE_LABELS,
    Q_CHART_LABELS,
    SIGNED_Q_CHART_KIND,
    SIGNED_Q_CREATION_ANNIHILATION_CONVENTION,
    SIGNED_Q_PROBE_LABELS,
    SIGNED_Q_SIGN_ORDER,
    Vituri2024DirectBuilderDependencyTrace,
    Vituri2024DirectDisplacedFockResponse,
    Vituri2024FunctionalReplayAnchorCheck,
    Vituri2024FunctionalReplayApproval,
    Vituri2024FunctionalReplayCallRecord,
    Vituri2024FunctionalReplayChoice,
    Vituri2024FunctionalReplayContract,
    Vituri2024FunctionalReplayMatrixLocalGate,
    Vituri2024FunctionalReplayMatrixStep,
    Vituri2024FunctionalReplayPayload,
    Vituri2024FunctionalReplayProviderProtocol,
    Vituri2024FunctionalReplayReceipt,
    Vituri2024FunctionalReplayReciprocity,
    Vituri2024FunctionalReplayScalarLocalGate,
    Vituri2024FunctionalReplayScalarStep,
    Vituri2024FunctionalReplayStatus,
    Vituri2024SignedQProbeChart,
    affine_anchor_inventory_sha256,
    direct_builder_dependency_archive_fingerprint,
    expected_array_payload_manifest_sha256,
    functional_provider_fingerprint,
    functional_replay_module_ast_manifest_sha256,
    q0_probe_inventory_sha256,
    replay_vituri2024_half_metal_hf_functional,
    signed_q_chart_inventory_sha256,
    signed_q_probe_inventory_sha256,
)
from .vituri2024_hf_scf_replay import (
    SCF_REPLAY_ADAPTER_ABI_FINGERPRINT,
    SCF_REPLAY_ARCHIVE_AUTHORITY_ABI_FINGERPRINT,
    SCF_REPLAY_ARCHIVE_AUTHORITY_METADATA_FIELDS,
    SCF_REPLAY_ARCHIVE_GENERATION_PHASE,
    SCF_REPLAY_ARCHIVE_SCHEMA_FINGERPRINT,
    SCF_REPLAY_PROVIDER_METADATA_FIELDS,
    SCF_REPLAY_SELECTED_HASH_FIELDS,
    SCF_REPLAY_V1_ABSOLUTE_TOLERANCE_MAXIMUM,
    SCF_REPLAY_V1_RELATIVE_TOLERANCE_MAXIMUM,
    SCF_REPLAY_VERIFIER_SCHEMA_FINGERPRINT,
    VITURI2024_SCF_BASELINE_COMMIT,
    VITURI2024_SCF_REPLAY_SCOPE,
    Vituri2024CoreCallableIdentity,
    Vituri2024CoreProvenance,
    Vituri2024CoreSourceManifest,
    Vituri2024ImmutableHistoricalSCFArchive,
    Vituri2024RestartCapabilityAudit,
    Vituri2024SCFArchiveAuthorityProtocol,
    Vituri2024SCFCallableManifest,
    Vituri2024SCFFinalRecomputationArchive,
    Vituri2024SCFProblemCallbackManifest,
    Vituri2024SCFReplayApproval,
    Vituri2024SCFReplayContract,
    Vituri2024SCFReplayProviderProtocol,
    Vituri2024SCFReplayReceipt,
    Vituri2024SCFReplayStatus,
    Vituri2024SCFReplayTolerance,
    Vituri2024SCFSeedTrajectoryArchive,
    Vituri2024SCFSelectedSource,
    Vituri2024SCFStateSnapshot,
    Vituri2024SCFStepArchive,
    Vituri2024SCFTransferSourceReceipt,
    default_vituri2024_scf_replay_tolerances,
    make_vituri2024_scf_replay_approval,
    replay_vituri2024_half_metal_hf_scf,
    scf_archive_authority_fingerprint,
    scf_archive_manifest_sha256,
    scf_dependency_archive_fingerprint,
    scf_provider_fingerprint,
    scf_replay_module_ast_manifest_sha256,
    verified_vituri2024_core_provenance,
    vituri2024_scf_callable_manifest,
    vituri2024_scf_problem_callback_manifests,
)
from .vituri2024_hf_pocket_replay import (
    POCKET_REFINEMENT_ARCHIVE_AUTHORITY_METADATA_FIELDS,
    POCKET_REFINEMENT_ARCHIVE_GENERATION_PHASE,
    POCKET_REFINEMENT_ARCHIVE_SCHEMA_FINGERPRINT,
    POCKET_REFINEMENT_EVALUATION_SCHEMA_FINGERPRINT,
    POCKET_REFINEMENT_EVIDENCE_MODEL,
    POCKET_REFINEMENT_LIFSHITZ_CONVENTION,
    POCKET_REFINEMENT_PROVIDER_METADATA_FIELDS,
    POCKET_REFINEMENT_REQUEST_SCHEMA_FINGERPRINT,
    POCKET_REFINEMENT_TOPOLOGY_CONVENTION,
    POCKET_REPLAY_V1_ABSOLUTE_TOLERANCE_EV,
    POCKET_REPLAY_V1_DIAGONAL_TOLERANCE_EV,
    POCKET_REPLAY_V1_FOCK_DECOMPOSITION_TOLERANCE_EV,
    POCKET_REPLAY_V1_HERMITICITY_TOLERANCE_EV,
    POCKET_REPLAY_V1_MESH_ABSOLUTE_TOLERANCE_INVERSE_ANGSTROM,
    POCKET_REPLAY_V1_MESH_RELATIVE_TOLERANCE,
    POCKET_REPLAY_V1_RELATIVE_TOLERANCE,
    VITURI2024_POCKET_REFINEMENT_REPLAY_SCOPE,
    VITURI2024_POCKET_REPLAY_PREREQUISITE_BASELINE_COMMIT,
    Vituri2024ArchivedPocketRefinementFields,
    Vituri2024DiscreteLifshitzEvidence,
    Vituri2024DiscreteLifshitzLaneEvidence,
    Vituri2024FrozenHFRefinementEvaluation,
    Vituri2024FrozenHFRefinementRequest,
    Vituri2024ImmutablePocketRefinementArchive,
    Vituri2024NestedNoWrapRefinementMesh,
    Vituri2024PocketBaseHashes,
    Vituri2024PocketCallableManifest,
    Vituri2024PocketPrerequisiteProvenance,
    Vituri2024PocketPrerequisiteSourceManifest,
    Vituri2024PocketRefinementArchiveAuthorityProtocol,
    Vituri2024PocketRefinementFieldHashes,
    Vituri2024PocketRefinementPrerequisites,
    Vituri2024PocketRefinementProviderProtocol,
    Vituri2024PocketRefinementReplayApproval,
    Vituri2024PocketRefinementReplayContract,
    Vituri2024PocketRefinementReplayReceipt,
    Vituri2024PocketRefinementReplayStatus,
    Vituri2024PocketTopologySignature,
    Vituri2024RefinedValleyTopologyEvidence,
    canonical_half_metal_hf_replay_receipt_fingerprint,
    canonical_scf_replay_receipt_fingerprint,
    make_vituri2024_pocket_refinement_replay_approval,
    pocket_refinement_archive_authority_fingerprint,
    pocket_refinement_archive_manifest_sha256,
    pocket_refinement_provider_fingerprint,
    pocket_refinement_replay_module_ast_manifest_sha256,
    replay_vituri2024_half_metal_hf_pocket_refinement,
    verified_vituri2024_pocket_prerequisite_provenance,
    vituri2024_pocket_callable_manifest,
    vituri2024_pocket_topology_signature,
    vituri2024_refinement_evidence_sha256,
)
from .vituri2024_hf_replay import (
    ACTIVE_BAND_STATES_GAUGE_SCOPE,
    ACTIVE_BAND_STATES_LAYOUT,
    ACTIVE_BAND_STATES_VALLEY_ORDER,
    CANONICAL_BASIS_KIND,
    FOCK_DECOMPOSITION_CONVENTION,
    INTERNAL_FLAVOR_ORDER,
    ORBITAL_INDEX_DESCRIPTOR_LABEL,
    ORBITAL_INDEX_DESCRIPTOR_SCHEMA_FINGERPRINT,
    ORBITAL_INDEX_DESCRIPTOR_SCHEMA_LABEL,
    REPLAY_ARRAY_CONVERSION,
    REPLAY_ARRAY_LAYOUT,
    REPLAY_ORBITAL_ORDER,
    REPLAY_PAYLOAD_SCHEMA_FINGERPRINT,
    REPLAY_RESIDUAL_NORM,
    Vituri2024HalfMetalHFBasePocketReplayEvidence,
    Vituri2024HalfMetalHFReplayHashes,
    Vituri2024HalfMetalHFReplayOccupationEvidence,
    Vituri2024HalfMetalHFReplayPayload,
    Vituri2024HalfMetalHFReplayProviderProtocol,
    Vituri2024HalfMetalHFReplayReceipt,
    Vituri2024HalfMetalHFReplayResiduals,
    Vituri2024HalfMetalHFReplayStatus,
    canonical_array_sha256,
    canonical_orbital_order_sha256,
    replay_vituri2024_half_metal_hf_arrays,
)
from .vituri2024_vertex import (
    ANTISYMMETRIZED_FULL_SUM_HAMILTONIAN_AREA_PREFACTOR,
    ANTISYMMETRIZED_VERTEX_EXCLUSIONS,
    KINEMATICS_AUTHORITY_SCOPE,
    KINEMATICS_PROVIDER_METADATA_STATUS,
    ORDERED_COEFFICIENT_EXCLUSIONS,
    ORDERED_FULL_SUM_HAMILTONIAN_AREA_PREFACTOR,
    PUBLISHED_PRB_PDF_SHA256,
    PauliShortCircuitReason,
    SelectionRule,
    VERTEX_AUTHORITY,
    VERTEX_GAUGE_BEHAVIOR,
    VERTEX_NORMALIZATION_IDENTITY,
    Vituri2024AntisymmetrizedVertexReceipt,
    Vituri2024Flavor,
    Vituri2024FourPointKinematicsReceipt,
    Vituri2024Orbital,
    Vituri2024OrderedCoefficientReceipt,
    Vituri2024PauliShortCircuitRecord,
    vituri2024_antisymmetrized_projected_vertex,
    vituri2024_ordered_projected_coefficient,
)
from .vituri2024 import (
    ACTIVE_BAND_INDEX_ZERO_BASED,
    ARXIV_IDENTIFIER,
    ARXIV_PDF_SHA256,
    ARXIV_SOURCE_SHA256,
    BASIS,
    PDF_AUTHORITY_PATH,
    SM_TEX_AUTHORITY_PATH,
    SM_TEX_SHA256,
    SPIN_STIFFNESS_CHECKPOINTS,
    UNRESOLVED_AUTHORITY,
    VITURI2024_PARAMETERS,
    VITURI2024_SPEC,
    ActiveBandEigensolution,
    ApproximatePaperCheckpoint,
    UnresolvedAuthorityItem,
    UnresolvedVituriAuthorityError,
    Vituri2024Parameters,
    Vituri2024Spec,
    c3_basis_operator,
    hamiltonian,
    six_band_hamiltonian,
    state_projector,
    third_lowest_active_band,
    third_lowest_active_projector,
)

__all__ = [
    "ACTIVE_BAND_INDEX_ZERO_BASED",
    "AFFINE_ANCHOR_LABELS",
    "ACTIVE_BAND_STATES_GAUGE_SCOPE",
    "ACTIVE_BAND_STATES_LAYOUT",
    "ACTIVE_BAND_STATES_VALLEY_ORDER",
    "ANTISYMMETRIZED_FULL_SUM_HAMILTONIAN_AREA_PREFACTOR",
    "ANTISYMMETRIZED_VERTEX_EXCLUSIONS",
    "DIAGONAL_HF_SOURCE_PROVIDER_STATUS",
    "DIRECT_DISPLACED_FOCK_CONSTRUCTION",
    "FINITE_AREA_PROVIDER_STATUS",
    "FINITE_Q_HESSIAN_NORMALIZATION",
    "FIXED_DENSITY_DIRECTION_CONVENTION",
    "FOCK_FIRST_DERIVATIVE_NORMALIZATION",
    "FOCK_OUTPUT_CONVENTION",
    "FUNCTIONAL_REPLAY_ABI_FINGERPRINT",
    "FUNCTIONAL_REPLAY_PAYLOAD_SCHEMA_FINGERPRINT",
    "FUNCTIONAL_REPLAY_PROVIDER_METADATA_FIELDS",
    "FUNCTIONAL_REPLAY_SCOPE",
    "FUNCTIONAL_REPLAY_VERIFIER_IMPLEMENTATION_SCHEMA_FINGERPRINT",
    "FORM_FACTOR_GAUGE_LABEL",
    "F_tau",
    "InteractionAuthorityKind",
    "INTERNAL_FLAVOR_ORDER",
    "KINEMATICS_AUTHORITY_SCOPE",
    "KINEMATICS_PROVIDER_METADATA_STATUS",
    "ORDERED_COEFFICIENT_EXCLUSIONS",
    "ORDERED_FULL_SUM_HAMILTONIAN_AREA_PREFACTOR",
    "ORBITAL_INDEX_DESCRIPTOR_LABEL",
    "ORBITAL_INDEX_DESCRIPTOR_SCHEMA_FINGERPRINT",
    "ORBITAL_INDEX_DESCRIPTOR_SCHEMA_LABEL",
    "PUBLISHED_PRB_PDF_SHA256",
    "PauliShortCircuitReason",
    "SelectionRule",
    "VERTEX_AUTHORITY",
    "VERTEX_GAUGE_BEHAVIOR",
    "VERTEX_NORMALIZATION_IDENTITY",
    "ARXIV_IDENTIFIER",
    "ARXIV_PDF_SHA256",
    "ARXIV_SOURCE_SHA256",
    "ActiveBandEigensolution",
    "ApproximatePaperCheckpoint",
    "BASIS",
    "CANONICAL_BASIS_KIND",
    "FOCK_DECOMPOSITION_CONVENTION",
    "PAPER_EPSILON",
    "PAPER_Q_TF_INVERSE_ANGSTROM",
    "PAPER_Q_TF_PER_A0",
    "PDF_AUTHORITY_PATH",
    "Q0Evaluation",
    "RPA_AREA_UNITS",
    "RPA_A_ELEMENT_EQUATION",
    "RPA_B_ELEMENT_EQUATION",
    "RPA_ELEMENT_AUTHORITY",
    "RPA_ELEMENT_NO_GO_LIMITS",
    "RPA_ELEMENT_UNITS",
    "RPA_VERTEX_UNITS",
    "SCF_REPLAY_ADAPTER_ABI_FINGERPRINT",
    "SCF_REPLAY_ARCHIVE_AUTHORITY_ABI_FINGERPRINT",
    "SCF_REPLAY_ARCHIVE_AUTHORITY_METADATA_FIELDS",
    "SCF_REPLAY_ARCHIVE_GENERATION_PHASE",
    "SCF_REPLAY_ARCHIVE_SCHEMA_FINGERPRINT",
    "SCF_REPLAY_PROVIDER_METADATA_FIELDS",
    "SCF_REPLAY_SELECTED_HASH_FIELDS",
    "SCF_REPLAY_V1_ABSOLUTE_TOLERANCE_MAXIMUM",
    "SCF_REPLAY_V1_RELATIVE_TOLERANCE_MAXIMUM",
    "SCF_REPLAY_VERIFIER_SCHEMA_FINGERPRINT",
    "Q0_PROBE_LABELS",
    "Q_CHART_LABELS",
    "RPAElementKind",
    "REPLAY_ARRAY_CONVERSION",
    "REPLAY_ARRAY_LAYOUT",
    "REPLAY_ORBITAL_ORDER",
    "REPLAY_PAYLOAD_SCHEMA_FINGERPRINT",
    "REPLAY_RESIDUAL_NORM",
    "SCALAR_HESSIAN_EQUATION",
    "SIGNED_Q_CHART_KIND",
    "SIGNED_Q_CREATION_ANNIHILATION_CONVENTION",
    "SIGNED_Q_PROBE_LABELS",
    "SIGNED_Q_SIGN_ORDER",
    "SM_TEX_AUTHORITY_PATH",
    "STORED_DENSITY_PAIRING",
    "SignedLane",
    "SM_TEX_SHA256",
    "SPIN_STIFFNESS_CHECKPOINTS",
    "UNRESOLVED_AUTHORITY",
    "V0",
    "VTF",
    "UnresolvedAuthorityItem",
    "UnresolvedVituriAuthorityError",
    "VITURI2024_HALF_METAL_HF_SCOPE",
    "VITURI2024_MAIN_TEX_SHA256",
    "VITURI2024_PARAMETERS",
    "VITURI2024_SPEC",
    "VITURI2024_SCF_BASELINE_COMMIT",
    "VITURI2024_SCF_REPLAY_SCOPE",
    "VITURI2024_TDHF_ASSEMBLY_AUTHORITY",
    "VITURI2024_TDHF_NO_GO_LIMITS",
    "VITURI2024_TDHF_Q_PROVENANCE",
    "VITURI2024_TDHF_RESPONSE_SCOPE",
    "VITURI2024_SCALAR_BLOCKERS",
    "VITURI2024_SCALAR_READINESS_AUTHORITY",
    "VITURI2024_SCALAR_READINESS_LOCKED_STRUCTURE_THRESHOLD",
    "VITURI2024_SCALAR_STATIC_HESSIAN_AUTHORITY",
    "VITURI2024_RESTRICTED_SCALAR_ALGEBRA_ABSOLUTE_TOLERANCE",
    "VITURI2024_RESTRICTED_SCALAR_ALGEBRA_RELATIVE_TOLERANCE",
    "VITURI2024_RESTRICTED_SCALAR_AUTHORITY",
    "VITURI2024_RESTRICTED_SCALAR_MAX_ORBITALS",
    "VITURI2024_RESTRICTED_SCALAR_WICK_ABSOLUTE_TOLERANCE",
    "VITURI2024_RESTRICTED_SCALAR_WICK_RELATIVE_TOLERANCE",
    "Vituri2024AntisymmetrizedVertexReceipt",
    "Vituri2024AttestedHalfMetalSourceArrays",
    "Vituri2024AttestedHalfMetalSourceReceipt",
    "Vituri2024BranchEnergyReceipt",
    "Vituri2024CoreCallableIdentity",
    "Vituri2024CoreProvenance",
    "Vituri2024CoreSourceManifest",
    "Vituri2024DensityFormFactorReceipt",
    "Vituri2024DiagonalHFTransitionReceipt",
    "Vituri2024FiniteDifferenceEvidenceReceipt",
    "Vituri2024FiniteAreaReceipt",
    "Vituri2024Flavor",
    "Vituri2024FourPointKinematicsReceipt",
    "Vituri2024FunctionalComponentReceipt",
    "Vituri2024DirectBuilderDependencyTrace",
    "Vituri2024DirectDisplacedFockResponse",
    "Vituri2024FunctionalReplayAnchorCheck",
    "Vituri2024FunctionalReplayApproval",
    "Vituri2024FunctionalReplayCallRecord",
    "Vituri2024FunctionalReplayChoice",
    "Vituri2024FunctionalReplayContract",
    "Vituri2024FunctionalReplayMatrixLocalGate",
    "Vituri2024FunctionalReplayMatrixStep",
    "Vituri2024FunctionalReplayPayload",
    "Vituri2024FunctionalReplayProviderProtocol",
    "Vituri2024FunctionalReplayReceipt",
    "Vituri2024FunctionalReplayReciprocity",
    "Vituri2024FunctionalReplayScalarLocalGate",
    "Vituri2024FunctionalReplayScalarStep",
    "Vituri2024FunctionalReplayStatus",
    "Vituri2024HFEnsembleReceipt",
    "Vituri2024HFGeometryReceipt",
    "Vituri2024HFReceiptSetStatus",
    "Vituri2024HFSCFPolicyReceipt",
    "Vituri2024HalfMetalHFBasePocketReplayEvidence",
    "Vituri2024HalfMetalHFProviderBinding",
    "Vituri2024HalfMetalHFProviderProtocol",
    "Vituri2024HalfMetalHFReplayHashes",
    "Vituri2024HalfMetalHFReplayOccupationEvidence",
    "Vituri2024HalfMetalHFReplayPayload",
    "Vituri2024HalfMetalHFReplayProviderProtocol",
    "Vituri2024HalfMetalHFReplayReceipt",
    "Vituri2024HalfMetalHFReplayResiduals",
    "Vituri2024HalfMetalHFReplayStatus",
    "Vituri2024HalfMetalHFSpec",
    "Vituri2024ImmutableHistoricalSCFArchive",
    "Vituri2024HalfMetalPaperTarget",
    "Vituri2024InteractionBinding",
    "Vituri2024InteractionChoiceReceipt",
    "Vituri2024LocalBandGapInfo",
    "Vituri2024MetallicityEvidenceReceipt",
    "Vituri2024Orbital",
    "Vituri2024OrderedCoefficientReceipt",
    "Vituri2024Parameters",
    "Vituri2024ProviderMetadataAttestedStatus",
    "Vituri2024RPAElementReceipt",
    "Vituri2024PauliShortCircuitRecord",
    "Vituri2024RestrictedScalarDFColumnEvidence",
    "Vituri2024RestrictedScalarOrbitalCrosswalk",
    "Vituri2024RestrictedScalarResiduals",
    "Vituri2024RestrictedScalarVertexBinding",
    "Vituri2024RestartCapabilityAudit",
    "Vituri2024SCFArchiveAuthorityProtocol",
    "Vituri2024SCFCallableManifest",
    "Vituri2024SCFCallbackReceipt",
    "Vituri2024SCFFinalRecomputationArchive",
    "Vituri2024SCFProblemCallbackManifest",
    "Vituri2024SCFReplayApproval",
    "Vituri2024SCFReplayContract",
    "Vituri2024SCFReplayProviderProtocol",
    "Vituri2024SCFReplayReceipt",
    "Vituri2024SCFReplayStatus",
    "Vituri2024SCFReplayTolerance",
    "Vituri2024SCFSeedReceipt",
    "Vituri2024SCFSeedTrajectoryArchive",
    "Vituri2024SCFSelectedSource",
    "Vituri2024SCFStateSnapshot",
    "Vituri2024SCFStepArchive",
    "Vituri2024SCFTransferSourceReceipt",
    "Vituri2024SignedQPair",
    "Vituri2024SignedQProbeChart",
    "Vituri2024SignedQTransitionInventoryPair",
    "Vituri2024Spec",
    "Vituri2024SharedFunctionalReceipt",
    "Vituri2024StateOverlapInvariant",
    "Vituri2024TDHFAssemblyContext",
    "Vituri2024TDHFSignedQAssemblyReceipt",
    "Vituri2024TDHFAssemblyReceipt",
    "Vituri2024TDHFScalarReadinessReceipt",
    "Vituri2024TDHFTransitionSourceBinding",
    "Vituri2024TDHFRestrictedScalarApproval",
    "Vituri2024TDHFRestrictedScalarReceipt",
    "Vituri2024TransitionInventory",
    "Vituri2024ValleyPocketEvidenceReceipt",
    "affine_anchor_inventory_sha256",
    "assemble_vituri2024_tdhf_signed_q",
    "build_vituri2024_tdhf_scalar_factory_readiness",
    "build_vituri2024_tdhf_scalar_readiness",
    "bind_vituri2024_interaction",
    "canonical_array_sha256",
    "canonical_orbital_order_sha256",
    "certify_vituri2024_tdhf_restricted_scalar",
    "c3_basis_operator",
    "default_vituri2024_scf_replay_tolerances",
    "direct_builder_dependency_archive_fingerprint",
    "expected_array_payload_manifest_sha256",
    "functional_provider_fingerprint",
    "functional_replay_module_ast_manifest_sha256",
    "hamiltonian",
    "make_vituri2024_scf_replay_approval",
    "make_vituri2024_tdhf_restricted_scalar_approval",
    "six_band_hamiltonian",
    "state_overlap_invariant",
    "state_projector",
    "third_band_density_form_factor",
    "vituri2024_tdhf_interaction_fingerprint",
    "third_lowest_active_band",
    "third_lowest_active_projector",
    "v0",
    "v_tf",
    "vituri2024_antisymmetrized_projected_vertex",
    "vituri2024_ordered_projected_coefficient",
    "q0_probe_inventory_sha256",
    "replay_vituri2024_half_metal_hf_arrays",
    "replay_vituri2024_half_metal_hf_functional",
    "replay_vituri2024_half_metal_hf_scf",
    "scf_archive_authority_fingerprint",
    "scf_archive_manifest_sha256",
    "scf_dependency_archive_fingerprint",
    "scf_provider_fingerprint",
    "scf_replay_module_ast_manifest_sha256",
    "signed_q_chart_inventory_sha256",
    "signed_q_probe_inventory_sha256",
    "vituri2024_rpa_a_element",
    "vituri2024_rpa_b_element",
    "vituri2024_v0",
    "verified_vituri2024_core_provenance",
    "vituri2024_scf_callable_manifest",
    "vituri2024_scf_problem_callback_manifests",
    "vituri2024_vtf",
    "vtf",
    "POCKET_REFINEMENT_ARCHIVE_AUTHORITY_METADATA_FIELDS",
    "POCKET_REFINEMENT_ARCHIVE_GENERATION_PHASE",
    "POCKET_REFINEMENT_ARCHIVE_SCHEMA_FINGERPRINT",
    "POCKET_REFINEMENT_EVALUATION_SCHEMA_FINGERPRINT",
    "POCKET_REFINEMENT_EVIDENCE_MODEL",
    "POCKET_REFINEMENT_LIFSHITZ_CONVENTION",
    "POCKET_REFINEMENT_PROVIDER_METADATA_FIELDS",
    "POCKET_REFINEMENT_REQUEST_SCHEMA_FINGERPRINT",
    "POCKET_REFINEMENT_TOPOLOGY_CONVENTION",
    "POCKET_REPLAY_V1_ABSOLUTE_TOLERANCE_EV",
    "POCKET_REPLAY_V1_DIAGONAL_TOLERANCE_EV",
    "POCKET_REPLAY_V1_FOCK_DECOMPOSITION_TOLERANCE_EV",
    "POCKET_REPLAY_V1_HERMITICITY_TOLERANCE_EV",
    "POCKET_REPLAY_V1_MESH_ABSOLUTE_TOLERANCE_INVERSE_ANGSTROM",
    "POCKET_REPLAY_V1_MESH_RELATIVE_TOLERANCE",
    "POCKET_REPLAY_V1_RELATIVE_TOLERANCE",
    "VITURI2024_POCKET_REFINEMENT_REPLAY_SCOPE",
    "VITURI2024_POCKET_REPLAY_PREREQUISITE_BASELINE_COMMIT",
    "Vituri2024ArchivedPocketRefinementFields",
    "Vituri2024DiscreteLifshitzEvidence",
    "Vituri2024DiscreteLifshitzLaneEvidence",
    "Vituri2024FrozenHFRefinementEvaluation",
    "Vituri2024FrozenHFRefinementRequest",
    "Vituri2024ImmutablePocketRefinementArchive",
    "Vituri2024NestedNoWrapRefinementMesh",
    "Vituri2024PocketBaseHashes",
    "Vituri2024PocketCallableManifest",
    "Vituri2024PocketPrerequisiteProvenance",
    "Vituri2024PocketPrerequisiteSourceManifest",
    "Vituri2024PocketRefinementArchiveAuthorityProtocol",
    "Vituri2024PocketRefinementFieldHashes",
    "Vituri2024PocketRefinementPrerequisites",
    "Vituri2024PocketRefinementProviderProtocol",
    "Vituri2024PocketRefinementReplayApproval",
    "Vituri2024PocketRefinementReplayContract",
    "Vituri2024PocketRefinementReplayReceipt",
    "Vituri2024PocketRefinementReplayStatus",
    "Vituri2024PocketTopologySignature",
    "Vituri2024RefinedValleyTopologyEvidence",
    "canonical_half_metal_hf_replay_receipt_fingerprint",
    "canonical_scf_replay_receipt_fingerprint",
    "make_vituri2024_pocket_refinement_replay_approval",
    "pocket_refinement_archive_authority_fingerprint",
    "pocket_refinement_archive_manifest_sha256",
    "pocket_refinement_provider_fingerprint",
    "pocket_refinement_replay_module_ast_manifest_sha256",
    "replay_vituri2024_half_metal_hf_pocket_refinement",
    "verified_vituri2024_pocket_prerequisite_provenance",
    "vituri2024_pocket_callable_manifest",
    "vituri2024_pocket_topology_signature",
    "vituri2024_refinement_evidence_sha256",
]

# Public authority-limited Vituri full-projector candidate adapter.
from . import vituri2024_tdhf_full_scalar as _vituri2024_tdhf_full_scalar
from .vituri2024_tdhf_full_scalar import *  # noqa: F401,F403

__all__ += list(_vituri2024_tdhf_full_scalar.__all__)

# Public authority-limited factorized Vituri full-projector functional kernel.
from . import vituri2024_tdhf_full_functional as _vituri2024_tdhf_full_functional
from .vituri2024_tdhf_full_functional import *  # noqa: F401,F403

__all__ += list(_vituri2024_tdhf_full_functional.__all__)

# Public generic-ABI callbacks and replay bridge for the factorized functional.
from . import vituri2024_tdhf_full_provider_callbacks as _vituri2024_tdhf_full_provider_callbacks
from .vituri2024_tdhf_full_provider_callbacks import *  # noqa: F401,F403

__all__ += list(_vituri2024_tdhf_full_provider_callbacks.__all__)

from . import vituri2024_tdhf_full_provider_bridge as _vituri2024_tdhf_full_provider_bridge
from .vituri2024_tdhf_full_provider_bridge import *  # noqa: F401,F403

__all__ += list(_vituri2024_tdhf_full_provider_bridge.__all__)

# Paper-direct active-band projected-Hamiltonian R=0 representative.
from . import vituri2024_projected_hamiltonian_reference as _vituri2024_projected_hamiltonian_reference
from .vituri2024_projected_hamiltonian_reference import *  # noqa: F401,F403

__all__ += list(_vituri2024_projected_hamiltonian_reference.__all__)

# Immutable candidate-artifact envelope for full-provider replay arrays.
from . import vituri2024_full_provider_artifact as _vituri2024_full_provider_artifact
from .vituri2024_full_provider_artifact import *  # noqa: F401,F403

__all__ += list(_vituri2024_full_provider_artifact.__all__)
