"""ABC-trilayer system adapters.

The Vituri projected vertex is authority-limited: it is derived from the
projected Hamiltonian rather than copied from literal Eq. C3, which is
internally inconsistent with its stated antisymmetry.  The fixed derivation
source is the pinned arXiv-v1 ``SM.tex``; the separate published-PRB evidence
is pinned to PDF SHA256
``2226e17ed95bd867607787b47343fe5fc77f2c30557023e349d86e55159c0765``.
The package does not claim a paper phase gauge or production/paper numerical
parity for that layer.  The local Vituri scalar-Hessian adapter maps the
derived vertex to paper C9.  Its separate signed-q adapter assembles four
independent local A/B lanes into the core typed generic-q classes without
repair, but remains diagnostic-only: diagonal-HF stationarity, real
mesh/area/q0/UV/CDW authority, and production/executable readiness are not
established.
"""

from .vituri2024_interaction import (
    FORM_FACTOR_GAUGE_LABEL,
    F_tau,
    InteractionAuthorityKind,
    PAPER_EPSILON,
    PAPER_Q_TF_INVERSE_ANGSTROM,
    PAPER_Q_TF_PER_A0,
    Q0Evaluation,
    V0,
    VTF,
    Vituri2024DensityFormFactorReceipt,
    Vituri2024InteractionBinding,
    Vituri2024InteractionChoiceReceipt,
    Vituri2024LocalBandGapInfo,
    Vituri2024StateOverlapInvariant,
    bind_vituri2024_interaction,
    state_overlap_invariant,
    third_band_density_form_factor,
    v0,
    v_tf,
    vituri2024_v0,
    vituri2024_vtf,
    vtf,
)
from .vituri2024_rpa import (
    DIAGONAL_HF_SOURCE_PROVIDER_STATUS,
    FINITE_AREA_PROVIDER_STATUS,
    RPA_AREA_UNITS,
    RPA_A_ELEMENT_EQUATION,
    RPA_B_ELEMENT_EQUATION,
    RPA_ELEMENT_AUTHORITY,
    RPA_ELEMENT_NO_GO_LIMITS,
    RPA_ELEMENT_UNITS,
    RPA_VERTEX_UNITS,
    SCALAR_HESSIAN_EQUATION,
    RPAElementKind,
    Vituri2024DiagonalHFTransitionReceipt,
    Vituri2024FiniteAreaReceipt,
    Vituri2024RPAElementReceipt,
    vituri2024_rpa_a_element,
    vituri2024_rpa_b_element,
)
from .vituri2024_tdhf import (
    VITURI2024_TDHF_ASSEMBLY_AUTHORITY,
    VITURI2024_TDHF_NO_GO_LIMITS,
    VITURI2024_TDHF_Q_PROVENANCE,
    VITURI2024_TDHF_RESPONSE_SCOPE,
    SignedLane,
    Vituri2024SignedQPair,
    Vituri2024SignedQTransitionInventoryPair,
    Vituri2024TDHFAssemblyContext,
    Vituri2024TDHFSignedQAssemblyReceipt,
    Vituri2024TransitionInventory,
    assemble_vituri2024_tdhf_signed_q,
)
from .vituri2024_vertex import (
    ANTISYMMETRIZED_FULL_SUM_HAMILTONIAN_AREA_PREFACTOR,
    ANTISYMMETRIZED_VERTEX_EXCLUSIONS,
    KINEMATICS_AUTHORITY_SCOPE,
    KINEMATICS_PROVIDER_METADATA_STATUS,
    ORDERED_COEFFICIENT_EXCLUSIONS,
    ORDERED_FULL_SUM_HAMILTONIAN_AREA_PREFACTOR,
    PUBLISHED_PRB_PDF_SHA256,
    PauliShortCircuitReason,
    SelectionRule,
    VERTEX_AUTHORITY,
    VERTEX_GAUGE_BEHAVIOR,
    VERTEX_NORMALIZATION_IDENTITY,
    Vituri2024AntisymmetrizedVertexReceipt,
    Vituri2024Flavor,
    Vituri2024FourPointKinematicsReceipt,
    Vituri2024Orbital,
    Vituri2024OrderedCoefficientReceipt,
    Vituri2024PauliShortCircuitRecord,
    vituri2024_antisymmetrized_projected_vertex,
    vituri2024_ordered_projected_coefficient,
)
from .vituri2024 import (
    ACTIVE_BAND_INDEX_ZERO_BASED,
    ARXIV_IDENTIFIER,
    ARXIV_PDF_SHA256,
    ARXIV_SOURCE_SHA256,
    BASIS,
    PDF_AUTHORITY_PATH,
    SM_TEX_AUTHORITY_PATH,
    SM_TEX_SHA256,
    SPIN_STIFFNESS_CHECKPOINTS,
    UNRESOLVED_AUTHORITY,
    VITURI2024_PARAMETERS,
    VITURI2024_SPEC,
    ActiveBandEigensolution,
    ApproximatePaperCheckpoint,
    UnresolvedAuthorityItem,
    UnresolvedVituriAuthorityError,
    Vituri2024Parameters,
    Vituri2024Spec,
    c3_basis_operator,
    hamiltonian,
    six_band_hamiltonian,
    state_projector,
    third_lowest_active_band,
    third_lowest_active_projector,
)

__all__ = [
    "ACTIVE_BAND_INDEX_ZERO_BASED",
    "ANTISYMMETRIZED_FULL_SUM_HAMILTONIAN_AREA_PREFACTOR",
    "ANTISYMMETRIZED_VERTEX_EXCLUSIONS",
    "DIAGONAL_HF_SOURCE_PROVIDER_STATUS",
    "FINITE_AREA_PROVIDER_STATUS",
    "FORM_FACTOR_GAUGE_LABEL",
    "F_tau",
    "InteractionAuthorityKind",
    "KINEMATICS_AUTHORITY_SCOPE",
    "KINEMATICS_PROVIDER_METADATA_STATUS",
    "ORDERED_COEFFICIENT_EXCLUSIONS",
    "ORDERED_FULL_SUM_HAMILTONIAN_AREA_PREFACTOR",
    "PUBLISHED_PRB_PDF_SHA256",
    "PauliShortCircuitReason",
    "SelectionRule",
    "VERTEX_AUTHORITY",
    "VERTEX_GAUGE_BEHAVIOR",
    "VERTEX_NORMALIZATION_IDENTITY",
    "ARXIV_IDENTIFIER",
    "ARXIV_PDF_SHA256",
    "ARXIV_SOURCE_SHA256",
    "ActiveBandEigensolution",
    "ApproximatePaperCheckpoint",
    "BASIS",
    "PAPER_EPSILON",
    "PAPER_Q_TF_INVERSE_ANGSTROM",
    "PAPER_Q_TF_PER_A0",
    "PDF_AUTHORITY_PATH",
    "Q0Evaluation",
    "RPA_AREA_UNITS",
    "RPA_A_ELEMENT_EQUATION",
    "RPA_B_ELEMENT_EQUATION",
    "RPA_ELEMENT_AUTHORITY",
    "RPA_ELEMENT_NO_GO_LIMITS",
    "RPA_ELEMENT_UNITS",
    "RPA_VERTEX_UNITS",
    "RPAElementKind",
    "SCALAR_HESSIAN_EQUATION",
    "SM_TEX_AUTHORITY_PATH",
    "SignedLane",
    "SM_TEX_SHA256",
    "SPIN_STIFFNESS_CHECKPOINTS",
    "UNRESOLVED_AUTHORITY",
    "V0",
    "VTF",
    "UnresolvedAuthorityItem",
    "UnresolvedVituriAuthorityError",
    "VITURI2024_PARAMETERS",
    "VITURI2024_SPEC",
    "VITURI2024_TDHF_ASSEMBLY_AUTHORITY",
    "VITURI2024_TDHF_NO_GO_LIMITS",
    "VITURI2024_TDHF_Q_PROVENANCE",
    "VITURI2024_TDHF_RESPONSE_SCOPE",
    "Vituri2024AntisymmetrizedVertexReceipt",
    "Vituri2024DensityFormFactorReceipt",
    "Vituri2024DiagonalHFTransitionReceipt",
    "Vituri2024FiniteAreaReceipt",
    "Vituri2024Flavor",
    "Vituri2024FourPointKinematicsReceipt",
    "Vituri2024InteractionBinding",
    "Vituri2024InteractionChoiceReceipt",
    "Vituri2024LocalBandGapInfo",
    "Vituri2024Orbital",
    "Vituri2024OrderedCoefficientReceipt",
    "Vituri2024Parameters",
    "Vituri2024RPAElementReceipt",
    "Vituri2024PauliShortCircuitRecord",
    "Vituri2024SignedQPair",
    "Vituri2024SignedQTransitionInventoryPair",
    "Vituri2024Spec",
    "Vituri2024StateOverlapInvariant",
    "Vituri2024TDHFAssemblyContext",
    "Vituri2024TDHFSignedQAssemblyReceipt",
    "Vituri2024TransitionInventory",
    "assemble_vituri2024_tdhf_signed_q",
    "bind_vituri2024_interaction",
    "c3_basis_operator",
    "hamiltonian",
    "six_band_hamiltonian",
    "state_overlap_invariant",
    "state_projector",
    "third_band_density_form_factor",
    "third_lowest_active_band",
    "third_lowest_active_projector",
    "v0",
    "v_tf",
    "vituri2024_antisymmetrized_projected_vertex",
    "vituri2024_ordered_projected_coefficient",
    "vituri2024_rpa_a_element",
    "vituri2024_rpa_b_element",
    "vituri2024_v0",
    "vituri2024_vtf",
    "vtf",
]
