from __future__ import annotations

"""Compatibility facade for TBG zero-field Hartree-Fock helpers."""

from ....core.hf import (
    HFOverlapBlockSet,
    compute_hf_energy,
    empty_overlap_block_set,
)
from ._hf_basis_overlap import (
    RestrictedHartreeFockRun,
    RestrictedHartreeFockState,
    build_h0_from_bm,
    build_interaction_hamiltonian,
    build_overlap_block_set,
    coulomb_unit,
    reciprocal_shift_labels,
    restricted_filling,
    restricted_occupied_bands_per_k,
    restricted_occupied_state_count,
    screened_coulomb,
)
from ._hf_restricted import (
    build_restricted_density_from_hamiltonian,
    build_restricted_hf_kernel,
    build_restricted_hf_problem,
    canonical_fig6_flavor_sequence,
    initialize_restricted_density,
    initialize_restricted_state,
    is_canonical_restricted_init,
    normalize_restricted_init_mode,
    oda_parametrization_restricted,
    run_restricted_hartree_fock,
    run_restricted_hf_from_bm_solution,
    update_restricted_density,
)
from ._hf_full import (
    build_full_density_from_hamiltonian,
    build_full_hf_kernel,
    build_full_hf_problem,
    canonical_fig6_state_sequence,
    initialize_full_density,
    initialize_full_state,
    normalize_full_init_mode,
    run_full_hartree_fock,
    run_full_hf_from_bm_solution,
)
from ._hf_diagnostics import (
    occupied_sigma_mean,
    offdiag_flavor_norm,
    restricted_gap_estimate,
)

__all__ = [
    "HFOverlapBlockSet",
    "RestrictedHartreeFockRun",
    "RestrictedHartreeFockState",
    "build_full_density_from_hamiltonian",
    "build_full_hf_kernel",
    "build_full_hf_problem",
    "build_h0_from_bm",
    "build_interaction_hamiltonian",
    "build_overlap_block_set",
    "build_restricted_density_from_hamiltonian",
    "build_restricted_hf_kernel",
    "build_restricted_hf_problem",
    "canonical_fig6_flavor_sequence",
    "canonical_fig6_state_sequence",
    "compute_hf_energy",
    "coulomb_unit",
    "empty_overlap_block_set",
    "initialize_full_density",
    "initialize_full_state",
    "initialize_restricted_density",
    "initialize_restricted_state",
    "is_canonical_restricted_init",
    "normalize_full_init_mode",
    "normalize_restricted_init_mode",
    "occupied_sigma_mean",
    "oda_parametrization_restricted",
    "offdiag_flavor_norm",
    "reciprocal_shift_labels",
    "restricted_filling",
    "restricted_gap_estimate",
    "restricted_occupied_bands_per_k",
    "restricted_occupied_state_count",
    "run_full_hartree_fock",
    "run_full_hf_from_bm_solution",
    "run_restricted_hartree_fock",
    "run_restricted_hf_from_bm_solution",
    "screened_coulomb",
    "update_restricted_density",
]
